os: linux
dist: focal
service:
- docker
language: python
python:
- '3.10'
env:
  global:
  - BUCKET_NAME=backup_bucket
  - AWS_ACCESS_KEY_ID=test
  - AWS_SECRET_ACCESS_KEY=test
branches:
  only:
  - main
install:
- pip install awscli awscli-local
script:
- cd tests/postgres15
- docker-compose up -d
- cd ..
- docker-compose up -d
- TIME=`date +%Y%m%dT%H%M"
- awslocal s3api get-object --bucket ${BUCKET_NAME} --key "postgres15_postgres_1/postgres15_postgres_1_${TIME}.sql.gz"
