services:
  backup:
    image: ithuan/multiple-databases-backup
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
      S3_ENDPOINT_URL:
      S3_REGION:
      S3_BUCKET:
      S3_ACCESS_KEY_ID:
      S3_SECRET_ACCESS_KEY:
      SCHEDULE:
      GPG_PUBLIC_KEY:
      KEEP_EVERY_BACKUP_IN_HOURS:
      KEEP_DAY_BACKUP_IN_DAYS:
      KEEP_MONTH_BACKUP_IN_MONTHS:
    restart: always
